#!/usr/bin/env python3
"""
test_instrument_lockstep.py — N1/N3: guard against drift between
questionnaire_instrument_source.md, questionnaire_items.csv, the shared
config, student_start.sh, and make_persona.py.

Checks (all stdlib, no network, no browser):
  1. questionnaire_items.csv has exactly EXPECTED_ITEMS rows.
  2. item codes unique and matching ^[A-Z]{1,4}\\d{1,3}$; no EX0x rows.
  3. constraint=1 exactly on VC01–VC05.
  4. options non-empty for single_select/multi_select, empty for
     likert5/short_text/long_text.
  5. construct blocks contiguous (each construct appears in one run).
  6. EXPECTED_ITEMS agrees across dtlab_config.env and the fallback
     literal in provisioning/student_start.sh.
  7. The ID pattern in build_form.gs accepts/rejects the same samples as
     the shared DTLAB_ID_PATTERN.
  8. N3: a persona generated by make_persona.py from a fabricated
     responses row yields exactly EXPECTED_ITEMS lines matching the
     '^- \\*\\*' pattern student_start.sh counts.

Run from repo root:  python3 tests/test_instrument_lockstep.py
"""

import csv
import importlib.util
import re
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CSV_PATH = REPO / "questionnaire" / "questionnaire_items.csv"
CODE_RE = re.compile(r"^[A-Z]{1,4}\d{1,3}$")


def _load_make_persona():
    spec = importlib.util.spec_from_file_location(
        "make_persona", REPO / "questionnaire" / "make_persona.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _load_agent_hidden_items():
    """The ONE authoritative exclusion set lives in make_persona.py."""
    return set(_load_make_persona().AGENT_HIDDEN_ITEMS)

failures = []


def check(cond, msg):
    if cond:
        print(f"  PASS: {msg}")
    else:
        print(f"  FAIL: {msg}")
        failures.append(msg)


def load_config():
    cfg = {}
    for raw in (REPO / "dtlab_config.env").read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        cfg[k.strip()] = v.strip().strip("'\"")
    return cfg


def main():
    cfg = load_config()
    expected = int(cfg.get("DTLAB_EXPECTED_ITEMS", "115"))

    with open(CSV_PATH, newline="", encoding="utf-8-sig") as f:
        rows = list(csv.DictReader(f))

    # 1–2: row count, code shape
    check(len(rows) == expected,
          f"CSV has exactly {expected} rows (got {len(rows)})")
    codes = [r["item_code"] for r in rows]
    check(len(codes) == len(set(codes)), "item codes are unique")
    bad = [c for c in codes if not CODE_RE.fullmatch(c)]
    check(not bad, f"all codes match ^[A-Z]{{1,4}}\\d{{1,3}}$ (bad: {bad[:5]})")
    check(not any(c.startswith("EX0") for c in codes),
          "no EX0x placeholder rows")

    # 3: constraint flags
    flagged = [r["item_code"] for r in rows
               if (r.get("constraint") or "").strip() == "1"]
    check(flagged == ["VC01", "VC02", "VC03", "VC04", "VC05"],
          f"constraint=1 exactly on VC01–VC05 (got {flagged})")

    # 4: options discipline
    bad_opts = []
    for r in rows:
        t, o = r["response_type"], (r.get("options") or "").strip()
        if t in ("single_select", "multi_select") and not o:
            bad_opts.append((r["item_code"], "missing options"))
        if t in ("likert5", "short_text", "long_text") and o:
            bad_opts.append((r["item_code"], "unexpected options"))
        if t in ("single_select", "multi_select") and o and \
                any(not part.strip() for part in o.split("|")):
            bad_opts.append((r["item_code"], "empty pipe segment"))
    check(not bad_opts, f"options match response_type contract ({bad_opts[:5]})")

    # 5: contiguous construct blocks
    seen_blocks, prev = [], None
    for r in rows:
        if r["construct"] != prev:
            seen_blocks.append(r["construct"])
            prev = r["construct"]
    check(len(seen_blocks) == len(set(seen_blocks)),
          "construct blocks are contiguous (no construct appears twice)")

    # 6: EXPECTED_ITEMS lockstep with student_start.sh's fallback literal
    start_sh = (REPO / "provisioning" / "student_start.sh").read_text()
    m = re.search(r'EXPECTED_ITEMS="\$\{DTLAB_EXPECTED_ITEMS:-(\d+)\}"',
                  start_sh)
    check(m is not None and int(m.group(1)) == expected == len(rows),
          "EXPECTED_ITEMS fallback in student_start.sh == config == CSV rows")

    # 6b: agent-hidden exclusion set (B10): exactly {PR02, PR08}, all in
    # the instrument, and student_start.sh's rendered-count gate subtracts
    # exactly that many items
    hidden = _load_agent_hidden_items()
    check(hidden == {"PR02", "PR08"},
          f"make_persona.AGENT_HIDDEN_ITEMS is exactly {{PR02, PR08}} "
          f"(got {sorted(hidden)})")
    check(hidden <= set(codes),
          "every agent-hidden item exists in the instrument")
    hm = re.search(r"AGENT_HIDDEN_COUNT=(\d+)", start_sh)
    check(hm is not None and int(hm.group(1)) == len(hidden),
          "student_start.sh AGENT_HIDDEN_COUNT == len(AGENT_HIDDEN_ITEMS)")
    rendered = expected - len(hidden)

    # 7: build_form.gs ID pattern semantically in sync with the config
    gs = (REPO / "questionnaire" / "build_form.gs").read_text()

    # 7a: the two consent checkboxes (docs/CONSENT_AND_DATA_USE.md >
    # "What you confirm") sit at the top of the Form build — layer 1 of
    # the layered consent capture (research_protocol §3)
    check("Understanding — I understand" in gs
          and "Consent — I consent" in gs,
          "build_form.gs carries both consent checkboxes (Understanding "
          "+ Consent)")
    check("CONSENT_AND_DATA_USE" in gs,
          "build_form.gs points at the consent & data-use sheet")
    # 7b (C1.6): the administrative sensitive-item opt-out is a FORM
    # field, not an instrument item — present, optional, and invisible
    # to the item machinery (its title prefix cannot parse as a code)
    mp = _load_make_persona()
    check(mp.SENSITIVE_ITEMS == {"D04", "D09", "D10", "D11", "D12"},
          "make_persona.SENSITIVE_ITEMS is exactly the five decided items")
    check(mp.SENSITIVE_ITEMS <= set(codes),
          "every sensitive item exists in the instrument")
    check("SENSITIVE_OPTOUT." in gs,
          "build_form.gs carries the administrative opt-out checkbox")
    check(".setRequired(false)" in gs,
          "the opt-out checkbox is OPTIONAL (everything else required)")
    check(mp.CODE_RE.match("SENSITIVE_OPTOUT. x") is None,
          "the opt-out title prefix can never parse as an item code")

    # 7c (C2.12): item-level Form validations — one VALIDATIONS map,
    # keys must be real instrument codes
    check("requireNumberBetween(16, 80)" in gs,
          "build_form.gs validates D05 (age) as a number 16-80")
    check("requireSelectAtMost(3)" in gs,
          "build_form.gs caps CB04 at 3 selections "
          "(CheckboxValidation; API name confirmed at Form build)")
    vkeys = re.findall(r"(?m)^\s*([A-Z]{1,4}\d{1,3}):\s*function", gs)
    check(set(vkeys) == {"D05", "CB04"},
          f"VALIDATIONS map keys are D05 + CB04 (got {sorted(vkeys)})")
    check(set(vkeys) <= set(codes),
          "every VALIDATIONS key is a real instrument code")

    gm = re.search(r"requireTextMatchesPattern\('([^']+)'\)", gs)
    check(gm is not None, "build_form.gs contains an ID validation pattern")
    if gm:
        gs_re = re.compile(gm.group(1).replace("\\\\", "\\"))
        cfg_re = re.compile(cfg["DTLAB_ID_PATTERN"])
        samples = [("DT2026-042", True), ("DT2026-999", True),
                   ("DT26-042", False), ("DTX026-042", False)]
        ok = all(bool(gs_re.fullmatch(s)) == bool(cfg_re.fullmatch(s)) == want
                 for s, want in samples)
        check(ok, "build_form.gs ID pattern and DTLAB_ID_PATTERN agree "
                  "on sample IDs")

    # 8 (content lockstep): parse §2 of the authoritative source document
    # and diff codes/order/constraints/types/options/wording against the
    # CSV — makes "source doc and CSV never diverge" an enforced property.
    src = (REPO / "questionnaire" /
           "questionnaire_instrument_source.md").read_text(encoding="utf-8")
    body = src.split("## 2. The instrument", 1)[1].split(
        "## 3. References", 1)[0]

    def norm(s):
        # typographic normalization only — dashes are flattened to
        # hyphens in the CSV transfer (AUTHORING_GUIDE convention), and
        # quote/ellipsis glyphs vary; anything beyond this is real drift
        s = (s.replace("’", "'").replace("‘", "'")
             .replace("“", '"').replace("”", '"')
             .replace("…", "...")
             .replace("–", "-").replace("—", "-").replace("−", "-"))
        return re.sub(r"\s+", " ", s).strip()

    TYPE_RE = re.compile(
        r"—\s*(single_select|multi_select|likert5|short_text|long_text)"
        r"[^\[\n]*(?:\[([^\]]*)\])?")
    ITEM_RE = re.compile(
        r"^- \*\*(?P<code>[A-Z]{1,4}\d{1,3})"
        r"(?P<constr> \[CONSTRAINT\])?\*\*\s*(?P<rest>.+)$")
    src_items, block_type, block_opts = {}, None, None
    for line in body.splitlines():
        if line.startswith("### Block"):
            tm = TYPE_RE.search(line)
            block_type = tm.group(1) if tm else None
            block_opts = ([o.strip() for o in tm.group(2).split(";")]
                          if tm and tm.group(2) else None)
            continue
        m = ITEM_RE.match(line.strip())
        if not m:
            continue
        rest = re.sub(r"\*\([^)]*\)\*\s*$", "", m.group("rest")).strip()
        tm = TYPE_RE.search(rest)
        if tm:
            itype = tm.group(1)
            iopts = ([o.strip() for o in tm.group(2).split(";")]
                     if tm.group(2) else None)
            text = rest[:tm.start()].strip(" —")
        else:
            itype, iopts = block_type, block_opts
            text = rest
        src_items[m.group("code")] = {
            "constraint": bool(m.group("constr")),
            "type": itype, "opts": iopts, "text": norm(text)}

    check(list(src_items) == codes,
          f"source-doc §2 codes match CSV codes and order "
          f"({len(src_items)} parsed)")
    src_constr = [c for c, it in src_items.items() if it["constraint"]]
    check(src_constr == flagged,
          f"source-doc [CONSTRAINT] markers == CSV constraint=1 "
          f"({src_constr})")
    diffs = []
    for r in rows:
        it = src_items.get(r["item_code"])
        if it is None:
            continue
        if it["type"] and it["type"] != r["response_type"]:
            diffs.append((r["item_code"], "type",
                          f"{it['type']} != {r['response_type']}"))
        if it["opts"] is not None:
            csv_opts = [o.strip() for o in
                        (r.get("options") or "").split("|")]
            if [norm(o) for o in it["opts"]] != [norm(o)
                                                 for o in csv_opts]:
                diffs.append((r["item_code"], "options",
                              f"{it['opts'][:3]}... != {csv_opts[:3]}..."))
        if it["text"] and norm(it["text"]).lower() not in \
                norm(r["question"]).lower():
            diffs.append((r["item_code"], "wording",
                          it["text"][:60]))
    check(not diffs,
          f"CSV wording/options/types match source-doc §2 "
          f"({len(diffs)} diffs; first: {diffs[:3]})")

    # 9 (N3): fabricate a Form response row, run make_persona.py, count the
    # exact pattern student_start.sh greps ('^- **CODE** ...'). Run BOTH
    # variants: opt-out unchecked (default) and checked (C1.6).
    import json as _json
    with tempfile.TemporaryDirectory() as tmp:
        td = Path(tmp)
        id_header = "Your course-issued participant ID (e.g. DT2026-042)"
        optout_header = ("SENSITIVE_OPTOUT. Optional: exclude my "
                         "sensitive demographic answers ...")
        u_header = "Understanding — I understand that my AI agent ..."
        c_header = "Consent — I consent to my pseudonymized data ..."
        headers = ["Timestamp", id_header, u_header, c_header,
                   optout_header] + \
                  [f"{r['item_code']}. {r['question']}" for r in rows]

        def write_responses(optout_val, understanding="I understand",
                            consent="I consent", blank_items=(),
                            drop_consent_cols=False):
            hdrs = [h for h in headers
                    if not (drop_consent_cols
                            and h in (u_header, c_header))]
            vals = {id_header: "DT2026-042", "Timestamp":
                    "2026-09-01 10:00:00", u_header: understanding,
                    c_header: consent, optout_header: optout_val}
            for r_ in rows:
                h_ = f"{r_['item_code']}. {r_['question']}"
                vals[h_] = ("" if r_["item_code"] in blank_items
                            else _fake_answer(r_))
            with open(td / "responses.csv", "w", newline="",
                      encoding="utf-8") as f:
                w = csv.writer(f)
                w.writerow(hdrs)
                w.writerow([vals.get(h, "") for h in hdrs])

        def gen(*extra):
            return subprocess.run(
                check=False,
                args=[sys.executable,
                      str(REPO / "questionnaire" / "make_persona.py"),
                      "--items", str(CSV_PATH),
                      "--responses", str(td / "responses.csv"),
                      "--student-id", "DT2026-042", "--outdir", str(td),
                      *extra],
                capture_output=True, text=True)

        # C2.13 consent gate: unchecked / missing-column refuse
        write_responses("", consent="")
        r = gen()
        check(r.returncode != 0 and "no consent on file" in r.stderr,
              "unchecked Consent box refuses persona generation")
        write_responses("", drop_consent_cols=True)
        r = gen()
        check(r.returncode != 0 and "no consent on file" in r.stderr,
              "missing consent columns refuse persona generation")
        # C2.13 completeness gate: a blank required item is a hard fail
        write_responses("", blank_items=("D05",))
        r = gen()
        check(r.returncode != 0 and "D05" in r.stderr,
              "blank required item hard-fails, naming the code")
        # --allow-incomplete: synthetic path only, prominent banner
        write_responses("", consent="", blank_items=("D05",))
        r = gen("--allow-incomplete")
        check(r.returncode == 0
              and "SYNTHETIC / OPT-OUT PERSONA" in
              (td / "persona_survey.md").read_text(),
              "--allow-incomplete generates with the SYNTHETIC banner")

        write_responses("")            # default: opt-out box unchecked
        r = gen()
        check(r.returncode == 0,
              f"make_persona.py succeeds on fabricated row ({r.stderr.strip()[:200]})")
        persona = td / "persona_survey.md"
        if persona.exists():
            ptext = persona.read_text()
            n = sum(1 for line in ptext.splitlines()
                    if re.match(r"^- \*\*", line))
            check(n == rendered,
                  f"persona_survey.md has {rendered} agent-visible '- **' "
                  f"item lines ({expected}-item instrument minus "
                  f"{len(hidden)} research-only; got {n}) — the count "
                  "student_start.sh checks")
            leaked = [c for c in hidden if f"**{c}**" in ptext]
            check(not leaked,
                  f"agent-hidden items absent from persona_survey.md "
                  f"(leaked: {leaked})")
            sens_present = [c for c in mp.SENSITIVE_ITEMS
                            if f"**{c}**" in ptext]
            check(sorted(sens_present) == sorted(mp.SENSITIVE_ITEMS),
                  "sensitive items RENDERED by default (no opt-out)")
            pcsv = (td / "persona_survey.csv").read_text()
            kept = [c for c in hidden if f",{c}," in pcsv]
            check(sorted(kept) == sorted(hidden),
                  "agent-hidden items still present in the research CSV")
            n_ans = sum(1 for line in ptext.splitlines()
                        if "(no answer)" in line)
            check(n_ans == 0, f"all fabricated answers mapped ({n_ans} unmapped)")
            meta = _json.loads((td / "persona_meta.json").read_text())
            check(meta == {"agent_hidden": sorted(hidden),
                           "sensitive_excluded": False,
                           "rendered_items": rendered},
                  f"persona_meta.json records the default render ({meta})")
        else:
            check(False, "persona_survey.md was generated")

        # opt-out CHECKED: exactly the five sensitive items leave the
        # agent copy; the research CSV is untouched
        write_responses("Exclude them from my agent's persona")
        r = gen()
        check(r.returncode == 0,
              "make_persona.py succeeds with the opt-out checked")
        ptext = persona.read_text()
        n = sum(1 for line in ptext.splitlines()
                if re.match(r"^- \*\*", line))
        check(n == rendered - len(mp.SENSITIVE_ITEMS),
              f"opt-out persona renders {rendered - len(mp.SENSITIVE_ITEMS)} "
              f"items (got {n})")
        check(not any(f"**{c}**" in ptext for c in mp.SENSITIVE_ITEMS),
              "sensitive items absent from the opt-out persona")
        check("sensitive demographic items excluded" in ptext,
              "opt-out persona header notes the exclusion")
        pcsv = (td / "persona_survey.csv").read_text()
        check(all(f",{c}," in pcsv for c in mp.SENSITIVE_ITEMS),
              "opt-out never touches the research CSV")
        meta = _json.loads((td / "persona_meta.json").read_text())
        check(meta["sensitive_excluded"] is True
              and meta["rendered_items"] == rendered - len(mp.SENSITIVE_ITEMS)
              and set(mp.SENSITIVE_ITEMS) <= set(meta["agent_hidden"]),
              f"persona_meta.json records the exclusion ({meta})")

    print()
    if failures:
        print(f"{len(failures)} FAILURE(S)")
        return 1
    print("Instrument lockstep: all checks pass.")
    return 0


def _fake_answer(item):
    t = item["response_type"]
    opts = (item.get("options") or "").split("|")
    if t == "likert5":
        return "4 - Agree a little"
    if t in ("single_select", "multi_select") and opts and opts[0].strip():
        return opts[0].strip()
    return "test answer"


if __name__ == "__main__":
    sys.exit(main())
